### ISSUE TITLE
havannah segfault

### ISSUE THREAD

**Issue by PolarGo** [tewalds/morat#5]
morat-havannah:

size 8
w b2
b e4
genmove w 3

segfaults after 3 seconds; assert d->empty() violated.

It happens 100% of the time; iow. it's completely reproducible.
Linux Ubuntu 14.04, amd64, g++ version 5.4.0

The segfault does not happen when the target is compiled in debug mode. This means that -O3
causes something bad that does not happen without optimization.

**Comment by tewalds** [comment]
I think this is fixed now.
